SELECT * FROM Member;
DESC Member;

CREATE TABLE Board
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
    body VARCHAR(2047) NOT NULL,
    memberId VARCHAR(255) NOT NULL,
    inserted TIMESTAMP DEFAULT NOW()
);
DESC Board;

SELECT * FROM Board;

ALTER TABLE Board
ADD FOREIGN KEY (MemberId) REFERENCES Member(id);

SELECT * FROM Board;

DELETE FROM Board
WHERE id='5';

SELECT * FROM Member;
